# version: '3'

# services:
#   nginx:
#     image: nginx:latest
#     volumes:
#       - ./var/www
#       - ./_docker/nginx/conf.d:/etc/nginx/conf.d
#     ports:
#       - 8876:80
#     depends_on:
#       - app
#     container_name: project_nginx

#   app:
#     build:
#       context: .
#       dockerfile: _docker/app/Dockerfile
#     volumes: 
#       - ./:/var/www 
#     depends_on:
#       - db
#     container_name: project_app

#   db:
#     image: postgres
#     restart: always
#     tty: true
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_DB: root
#       POSTGRES_PASSWORD: root
#       PGDATA: /var/lib/postgresql/data/pgdata
#       POSTGRES_HOST_AUTH_METHOD: trust
#     volumes:
#       - ./docker/pgsql/datadir:/var/lib/mysql

# services:
#     redis:
#       image: redis:alpine
#       container_name: JustBuy-redis

#     postgres:
#       image: postgres:10
#       container_name: JustBuy-postgres
#       volumes:
#          - "./sourcefiles/postgres:/var/lib/postgresql/data"
#       environment:
#         - POSTGRES_USER=postgres
#         - POSTGRES_PASSWORD=root
#         - POSTGRES_DB=root
#       ports:
#        - "5432:5432"
#       networks:
#             testing_net:
#                 ipv4_address: 172.28.1.2
#     webserver:
#       image: nginx:alpine
#       container_name: JustBuy-webserver
#       working_dir: /application
#       volumes:
#           - ./application:/application
#           - ./sourcefiles/nginx:/etc/nginx/conf.d
#       ports:
#        - "80:80"
#       networks:
#             testing_net:
#                 ipv4_address: 172.28.1.3

#     php-fpm:
#       build: sourcefiles/php-fpm
#       container_name: JustBuy-php-fpm
#       working_dir: /application
#       volumes:
#         - ./application:/application
#         - ./sourcefiles/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
#       networks:
#           testing_net:
#               ipv4_address: 172.28.1.4
# networks:
#     testing_net:
#         ipam:
#             driver: default
#             config:
#                 - subnet: 172.28.0.0/16
